In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/gravier/gravier_csv/alon.csv')

In [3]:
df

,x.X1,x.X2,x.X3,x.X4,x.X5,x.X6,x.X7,x.X8,x.X9,x.X10,...,x.X1992,x.X1993,x.X1994,x.X1995,x.X1996,x.X1997,x.X1998,x.X1999,x.X2000,y
0,8589.42,5468.24,4263.41,4064.94,1997.89,5282.33,2169.72,2773.42,7526.39,4607.68,...,67.56,259.91,138.90,88.23,39.67,67.83,75.68,83.52,28.70,t
1,9164.25,6719.53,4883.45,3718.16,2015.22,5569.91,3849.06,2793.39,7017.73,4802.25,...,92.24,96.28,150.59,82.24,85.03,152.20,186.57,44.47,16.77,n
2,3825.71,6970.36,5369.97,4705.65,1166.55,1572.17,1325.40,1472.26,3296.95,2786.58,...,82.72,31.10,193.92,76.97,224.62,31.23,42.66,16.09,15.16,t
3,6246.45,7823.53,5955.84,3975.56,2002.61,2130.54,1531.14,1714.63,3869.79,4989.41,...,41.68,5.93,183.01,74.53,67.71,48.34,42.52,49.98,16.09,n
4,3230.33,3694.45,3400.74,3463.59,2181.42,2922.78,2069.25,2948.58,3303.37,3109.41,...,76.60,161.35,61.70,54.56,223.36,73.10,57.60,7.49,31.81,t
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,4972.17,4173.92,3668.53,1567.56,1570.44,3466.81,2106.50,1535.76,1887.62,3519.60,...,6.45,156.45,93.95,86.91,95.44,31.19,57.15,13.96,10.55,t
58,9112.37,6824.49,5982.85,3147.04,4847.31,11222.68,6333.47,4299.50,4644.44,5888.55,...,35.88,342.65,84.75,60.27,143.88,9.00,106.88,23.20,32.17,t
59,6730.63,3472.13,2559.46,2624.69,1596.22,4372.79,3798.53,1026.48,3512.33,3243.17,...,119.96,111.60,166.76,130.46,124.25,96.47,133.52,93.10,7.43,n
60,6234.62,4005.30,3093.68,3183.09,1795.31,3940.85,2019.85,1406.65,2927.79,2177.32,...,85.26,206.54,80.45,104.81,180.94,68.93,118.20,32.69,23.27,t
61,7472.01,3653.93,2728.22,3494.48,2404.67,5791.61,2876.42,2150.96,3767.00,2685.30,...,63.64,437.65,178.27,153.85,269.44,67.86,77.22,49.86,39.63,n

In [4]:
df_y = df['y']
set(df_y)

{'n', 't'}